#!/bin/bash

if (( $# < 4 )); then
  echo "kubectl appmetrics show <kind> <instance> <namespace-in-which-the-app-is-created> <kubeconfig>"
  exit 0
fi

# Requirement 4.1
# Take following inputs in order
# kind
# instance
# namespace
# kubeconfig


URL=`kubectl appurl $kind $instance $namespace -k $kubeconfig`
URL=$(echo $URL | sed "s/[][]//g" | sed "s/'//g")
echo $URL 

echo "---"
curl $URL/greetings
echo "---"
curl $URL/listcontents
echo "---"
curl $URL/getk8sobjects
echo "---"

# Requirement 4.2
# Call the metrics endpoint

